---
name: apiary-django

services:
  app:
    build: .
    image: "rrchnm/apiary-django"
    ports:
      - 8000:8000
    volumes:
      - dj-data:/app
     #- .:/app
    environment:
      - DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_SECRET_KEY=thisisnotasecretkey
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost
      - DJANGO_SUPERUSER_EMAIL=PLACEHOLDER
      - DJANGO_SUPERUSER_USERNAME=PLACEHOLDER
      - DJANGO_SUPERUSER_PASSWORD=PLACEHOLDER
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=apiary-django
      - DB_USER=apiary-django
      - DB_PASSWORD=password
      - ALLAUTH_ORCID_CLIENT_ID=PLACEHOLDER
      - ALLAUTH_ORCID_CLIENT_SECRET=PLACEHOLDER
      - ALLAUTH_GITHUB_CLIENT_ID=PLACEHOLDER
      - ALLAUTH_GITHUB_CLIENT_SECRET=PLACEHOLDER
      - ALLAUTH_SLACK_CLIENT_ID=PLACEHOLDER
      - ALLAUTH_SLACK_CLIENT_SECRET=PLACEHOLDER
      - OBJ_STORAGE=True
      - OBJ_STORAGE_ACCESS_KEY_ID=PLACEHOLDER
      - OBJ_STORAGE_SECRET_ACCESS_KEY=PLACEHOLDER
      - OBJ_STORAGE_BUCKET_NAME=PLACEHOLDER
      - OBJ_STORAGE_ENDPOINT_URL=https://dev.obj.rrchnm.org
    command: >
        sh -c "uv run manage.py init_superuser &&
               uv run manage.py migrate --database=default --verbosity=1 &&
               uv run manage.py migrate bom --database=bom_db --verbosity=1 &&
               uv run manage.py migrate connthreads --database=connthreads_db --verbosity=1 &&
               uv run manage.py migrate mappingviolence --database=mappingviolence_db --verbosity=1 &&
               uv run manage.py migrate relec --database=relec_db --verbosity=1 &&
               uv run manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18
    ports:
      - 5432:5432
    volumes:
      - ./postgres_initdb:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=apiary-django
      - POSTGRES_USER=apiary-django
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiary-django"]
      interval: 2s
      timeout: 5s
      retries: 3

volumes:
  dj-data:
  pg-data:
