# Generated by Django 5.2.8 on 2026-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'denomination',
                'db_table_comment': 'Demonination records for Religious Ecologies project',
            },
        ),
    ]
