# Generated by Django 5.2.8 on 2026-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('circulation', models.IntegerField()),
            ],
            options={
                'db_table': 'textile',
                'db_table_comment': 'Textile records for Connecting Threads project',
            },
        ),
    ]
