# Generated by Django 5.2.8 on 2026-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimony_date', models.DateField()),
                ('crime', models.CharField(max_length=200)),
                ('claim', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Witnesses',
                'db_table': 'witness',
                'db_table_comment': 'Witness testimony records for Mapping Violence project',
            },
        ),
    ]
