# Generated by Django 5.2.8 on 2026-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'project',
                'db_table_comment': 'Project table',
            },
        ),
    ]
