# Generated by Django 5.2.8 on 2026-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'mortalitybill',
            },
        ),
    ]
